# Generated by Django 6.0.3 on 2026-03-09 22:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='countries_origin',
            new_name='country_origin',
        ),
        migrations.AlterField(
            model_name='submission',
            name='countries_residence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
    ]
