# Generated by Django 6.0.3 on 2026-03-09 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='countries_origin',
            new_name='country_origin',
        ),
        migrations.AlterField(
            model_name='submission',
            name='countries_residence',
            # PostgreSQL keeps its array column; SQLite stores the same list as JSON.
            field=settings.DATABASE_HANDLER.residence_field(),
        ),
    ]
