# Generated by Django 6.0.3 on 2026-03-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_countries_origin_submission_country_origin_and_more'),
        ('submissions', '0002_submissiontext'),
    ]

    operations = [
    ]
