# Generated by Django 6.0.3 on 2026-03-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_merge_20260322_2134'),
        ('submissions', '0003_submission_submission_type'),
    ]

    operations = [
    ]
