# Generated by Django 5.2.12 on 2026-03-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, max_length=32)),
                ("description", models.TextField(blank=True)),
                ("artist_name", models.CharField(max_length=255)),
                ("pronouns", models.CharField(max_length=128)),
                ("short_bio", models.TextField()),
                ("socials", models.CharField(blank=True, max_length=500)),
                ("countries_origin", models.TextField()),
                ("countries_residence", models.TextField(blank=True)),
                ("language", models.CharField(default="English", max_length=64)),
                ("allow_translation", models.BooleanField(default=False)),
                (
                    "text_file",
                    models.FileField(
                        blank=True, null=True, upload_to="submissions/texts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="submissions/visuals/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visuals",
                        to="ragezine_portal.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
